require:
  - rubocop-rails

AllCops:
  NewCops: disable
  TargetRubyVersion: 3.2.2
  TargetRailsVersion: 7.1

# == Style

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - db/schema.rb

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/NumericLiterals:
  Enabled: true
  Exclude:
    - db/schema.rb

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/WordArray:
  Enabled: true
  Exclude:
    - db/schema.rb

# == Lint

Lint/AmbiguousBlockAssociation:
  Enabled: true
  AllowedMethods: [change]

Lint/ConstantDefinitionInBlock:
  Enabled: false

# == Layout

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

# == Metrics
Metrics/BlockLength:
  Enabled: false
